//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACT_LAB_2_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empl4
    {
        public int employeer_id { get; set; }
        public string employeer_name { get; set; }
        public string employeer_surname { get; set; }
        public string employeer_middlename { get; set; }
        public string post_name { get; set; }
        public float post_salary { get; set; }
    }
}
